StreamDecayCoefficient: 0.1 #decay coefficient per km is StreamDecayCoefficient*flow**StreamDecayExponent with flow in m3/s
StreamDecayExponent: -0.7 #decay coefficient per km is StreamDecayCoefficient*flow**StreamDecayExponent with flow in m3/s
